spring:
  application:
    name: shortener

  datasource:
    url: jdbc:postgresql://localhost:5433/shortener
    username: shortener
    password: shortener
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    open-in-view: false

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

server:
  port: 8080
  error:
    include-message: always

app:
  base-url: http://localhost:8080
  jwt:
    secret: "change-me-to-a-very-long-secret-key-at-least-32-bytes-long-please"
    access-token-expiration-ms: 3600000        # 1 час
    refresh-token-expiration-ms: 604800000     # 7 дней
  code:
    length: 7
    max-retries: 5

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
  api-docs:
    path: /v3/api-docs

logging:
  level:
    com.example.shortener: DEBUG
    org.springframework.security: INFO